apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sal-application
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sal-application
    spec:
      containers:
      - name: sal-application
        image: ravibhim/sal-application:v8
        ports:
        - containerPort: 8080
